name: Publish to npm
on:
  push:
    branches:
      - main

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hanseartic'
      - run: yarn install --ignore-scripts --frozen-lockfile --prod
      - name: Get current package version
        run: echo "NPM_VERSION=$(npm ls --json 2> /dev/null | jq -r .version)" >> $GITHUB_ENV
      - name: publish to GH packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@hanseartic'
      - name: publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
      - name: Tag branch with current package version
        uses: negz/create-tag@v1
        with:
          version: "v${{ env.NPM_VERSION }}"
          message: "v${{ env.NPM_VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
